export { BeltService } from './belt.service';
export { CapabilityService } from './capability.service';
export { ExamService } from './exam.service';
export { LocationService } from './location.service';
export { RoleService } from './role.service';
export { StudentService } from './student.service';
export { SubmissionFileService } from './submission-file.service';
export { SubmissionService } from './submission.service';
export { UserService } from './user.service';
